version: "3"
services:
  web:
    build: ./nginx
    depends_on: 
      - app
    ports:
      - 8080:80
  app:
    build: ./go-app
    command: revel run -a app
    volumes:
      - ./go-app/app:/go/src/app
    depends_on: 
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306